### ISSUE TITLE
完整颜色表格

### ISSUE THREAD

**Issue by monicfenga** [fengT-T/Mikuconsole#3]
| \ | Background | Foreground | Color0 | Color1 | Color2 | Color3 | Color4 | Color5 | Color6 | Color7 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Faint | `rgb(238,238,238)` | `rgb(95,99,100)` | `rgb(168,170,171)` | `rgb(120,50,40)` | `rgb(11,193,193)` | `rgb(217,160,27)` | `rgb(27,102,143)` | `rgb(97,74,115)` | `rgb(41,168,182)` | `rgb(37,218,134)` |
| Normal | `rgb(255,255,255)` | `rgb(129,129,129)` | `rgb(139,139,139)` | `rgb(243,103,10)` | `rgb(5,216,202)` | `rgb(243,216,7)` | `rgb(32,143,207)` | `rgb(140,101,207)` | `rgb(1,203,197)` | `rgb(16,223,161)` |
| Intense | `rgb(255,255,255)` | `rgb(113,113,113)` | `rgb(126,126,126)` | `rgb(255,76,16)` | `rgb(8,193,187)` | `rgb(231,208,29)` | `rgb(60,138,221)` | `rgb(151,47,255)` | `rgb(19,208,202)` | `rgb(25,250,175)` |

![颜色表格的可视化效果，如果看不到的话，请参考以上表格。](https://user-images.githubusercontent.com/39868412/225793770-acef1018-c62e-4039-ba8f-b61844dd2fba.PNG)

供其他终端，或者能自定义配色的软件，或者网站设计配色的参考。

---

Color 2,4,7适合作为强调色，Color 4,5,6适合作为辅助色。

渐变色可以做同色系的标准色到Intense色（比如Color 7到Color 7 Intense），也可以做不同颜色之间的（比如Color 2到Color 7）。

背景的不透明度为0.84（84%），且需要实现背景模糊效果（如果能实现的话）。 

在白色背景下，只有Color7 Intense可能看不清楚。在黑色背景下，所有颜色都很清晰可辨。

> 我觉得列成表格能帮到其他人，故分享。

**Comment by monicfenga** [comment]
![Web Example](https://user-images.githubusercontent.com/39868412/225798049-5019cc41-9f8f-4d59-b47d-6732a80306e3.png)

**Comment by fengT-T** [comment]
感谢分享，下周整理一下。
